<a href="https://colab.research.google.com/github/Zactyz/AI-Repo/blob/master/HW_4/Homework_4_problems_1_and_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Homework 4 - Zachary Zimmerman

##Problem 1 - convolutions

In [0]:
import numpy as np

#function takes as input input_mat and kernel_mat and outputs desired output_mat.
def conv2d(input_mat, kernel_mat):

  # assure dimensions are not negative
  if input_mat.shape[0] < kernel_mat.shape[0]:
    output_mat = []
    return output_mat

  # dimensions of output
  x = input_mat.shape[0] - kernel_mat.shape[0] + 1
  y = kernel_mat.shape[0]

  # create output matrix using dimensions, filled with zeros
  output_mat = np.zeros((x, x))

  # use loops to multiply and sum by the kernal
  for i in range(x):
    for j in range(x):
      output_mat[i,j] = np.sum(np.multiply(input_mat[i:i+y, j:j+y], kernel_mat))



  return output_mat

###Test Cases (provided in assignment)

In [0]:
from scipy import signal
import numpy as np

input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])



for i in range(len(input_mat)):
  # uncomment line for student code testing
  output_mat = conv2d(input_mat[i], kernel_mat[i])

  # uncomment lines below (and comment line above) for generating test cases.
  #if input_mat[i].shape[0] < kernel_mat[i].shape[0]:
    #output_mat = []
  #else:
    #output_mat = signal.convolve2d(input_mat[i], kernel_mat[i], mode='valid')

  print(output_mat)
  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")


[[2. 4. 2.]
 [4. 2. 4.]
 [2. 4. 2.]]
Correct output!

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
Correct output!

[[ 1. -1.  0.]
 [-1.  1. -1.]
 [ 0. -1.  1.]]
Correct output!

[[4.]]
Correct output!

[]
Correct output!



##Problem 2 - max pooling

In [0]:
import numpy as np

# function that takes as input input_mat and s and outputs desired output_mat using max pooling operation
def maxpooling2d(input_mat, s):

  # check if input_mat is not square, and add 0s to make square
  if input_mat.shape[0] != input_mat.shape[1]:
    if input_mat.shape[0] - input_mat.shape[1] > 0:
      pad = np.zeros(input_mat.shape[1])
      input_mat = np.column_stack((input_mat, pad))
    elif input_mat.shape[0] - input_mat.shape[1] < 0:
      pad = np.zeros(input_mat.shape[1])
      input_mat = np.vstack((input_mat, pad))
  
  # add 0s using s if uneven
  pad = input_mat.shape[0] % s
  input_mat = np.pad(input_mat, pad)

  # create output_mat
  output_dim = (int(input_mat.shape[0]/s), int(input_mat.shape[0]/s))
  output_mat = np.zeros(output_dim)
  
  for i in range(0, input_mat.shape[0], s):
    for j in range(0, input_mat.shape[0], s):
      x = int(i/s)
      y = int(j/s)

      output_mat[x][y] = np.max(input_mat[i:i+s, j:j+s])

  return output_mat

###Test Cases (provided in assignment)

In [0]:
import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
  #output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")


[[4. 2.]
 [2. 4.]]
Correct output!
[[4. 2. 5.]
 [2. 4. 5.]
 [1. 3. 2.]]
Correct output!
